### ISSUE TITLE
Bug Tracker - dev.vts.nextdroid.com [8a0718b]

### ISSUE THREAD

**Issue by dgandhiAM** [NextDroid/potree#134]
@arjunskND @jstrinkaND 
Add any issues here.  @bcasselsND will fix and/or generate sub-tasks as necessary.

- [x] (DG) Changing time window setting doesn't live-update highlighting.  Requires pushing play.
- [x] (DG) When scrolling with your mouse hovering over the time slider, the time should increment forward (scroll-up) and back (scroll-down).  The forward increment is equal to the the positive time window value, and the negative increment is equal to the negative time window value.  If either value is zero, the increment/decrement should be set to 0.05.
- [x] (JS) Checkboxes should disable/enable all checkboxes in their downstream tree. 
- [x] ~(JS) Downloaded plots (and eventually data to make plots) should have descriptive names, currently all are named "Newplot"~ Moving to separate issue
- [x] ~Field of view slider is not updated when you zoom in/out with mouse wheel.~ FOV and mouse wheel zooming control two different variables

**Comment by bcasselsND** [comment]
@dgandhiAM Current code is looking for "enter" key, and that seems to work.

What behavior would you like? Reasonable choices are onChange and onBlur. onChange will move every keystroke. onBlur will wait until you stop typing, and move focus.

**Comment by dgandhiAM** [comment]
@bcasselsND @arjunskND Updated this issue to include scrolling on time slider functionality being lost

**Comment by arjunskND** [comment]
Hey @bcasselsND , @dgandhiAM and I noticed a bug in potree with loading tracks. If you try one of the SLICE datasets in the perception bucket, you will notice that 

1) Tracks don't load right away in the left panel. The playbar does not show downloading tracks.fb in its progress (this may not be a bug) and 
2) The tracks only are visible when we change the upper and lower bounds of the time window (this seems to  me like a bug)

I may have also noticed a problem with the track loader for my local tracks (for my local point cloud). I want to confirm by comparing a pervious commit of potree

**Comment by bcasselsND** [comment]
@jstrinkaND -- about plot names. There is not currently a name for plots. So someone would have to provide a name, or we can make one up, from the description, or something like that. We could add a "name" field to the [specification of a plot](https://github.com/NextDroid/VeritasApplication/blob/develop/imports/client/app/components/EvaluationSpecs.js#L23). But that feels like extra work, for something that is only sometimes used.

Now that you see the situation, what do you propose?
