### ISSUE TITLE
Refine potree file loading

### ISSUE THREAD

**Issue by bcasselsND** [NextDroid/potree#162]
[Nick's PR](https://github.com/NextDroid/potree/pull/155/files) does a lot of good stuff.

Make it even better:
- [x] Filter out directories we never look at -- 1_Viz, 6_Logs
- [ ] Do some operations in parallel, to speed up loading.
- [ ] file loading
- [x]  (issue with rem and control point loading)
- [ ] local data #168
- [x] tracks issues Veritas#326
- [x] general clean up

**Comment by nmhaddadND** [comment]
potree #168 ties into this too. Getting an error as a result of that merge when running local data. Not sure if these issues should be together.
