### ISSUE TITLE
Update transforms in potree to accomodate VAT parameter changes

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#193]
Following on changes in Veritas#294, the reconstruction pipeline has been updated so accordingly the transforms in the shader used by the calibration panels needs to be updated as well.

Brain dump:
 - [x] Add new transform chain to shader to stay in sync with changes in Veritas#294
 - [x] Retain backwards compatibility with existing transform chain for older datasets
 - [x] Load in additional extrinsics files (if available)
 - [x] Logic of downloading version 2/3 of the calibration corrections file
 - [x] Think about related updates to calibration panels (makes sense to use smaller values? Move values to degrees instead of radians?
 - [x] Also think about reducing error accumulation by chaining multiple transforms together (see Veritas#371)

**Comment by vrajur-nd** [comment]
All issues have been closed, epic is complete.
