### ISSUE TITLE
Integrating Streaming/Calibration Functionality into Potree

### ISSUE THREAD

**Issue by vrajur-nd** [NextDroid/potree#90]
An incremental approach towards integrating this functionality has 3 main sub-tasks. A summary of the estimated level of effort is included below, and a more detailed estimate can be viewed here: [LoE-Streaming-Player (Dropbox)](https://www.dropbox.com/work/My%20Documents?preview=LoE-Streaming-Player.odt).

# Level of Effort Estimate 

## Sub-Task 1: Integrating Calibration Functionality
_Top Down Time Estimate: (3-5 days)_

#### Tasks: 
 - [x] Setup PotreeConverter to process VehicleFrameCloud (1-2 hr)
 - [x] Create "Calibration Mode" for potree (1-2 hr)
 - [x] Add potree code to associate rtk pose to potree loaded point (5-7 hrs)
 - [x] Shader updates for enabling calibration (2-3 hrs)

#### Total Time (Bottom Up):
 - Time Estimate: 9-14 hrs
 - Time Estimate (100% safety margin): 18-28 hrs

## Sub-Task 2: Integrating Streaming Functionality (for flatbuffers):

_Top Down Time Estimate: 2-4 weeks after calibration solution _

#### Tasks:

 - [ ] Create a header file to index flatbuffer pointcloud data (VehicleFrameCloud.fb) (1-2 hrs)
 - [ ] Buffer Streaming: Define logic for start/end time of buffer and send stream request (1-2 hrs)
 - [ ] Buffer Streaming: Handle incoming data and store in buffer - 2 Options:
   - [ ] Option 1: Use file stream (4-8 hrs)
   - [ ] Option 2: Use media segments (8-16 hrs)
 - [ ] Load data into potree pointcloud - 2 Options:
  - [ ] Option 1: Pointcloud attribute swapping (6-8 hrs)
  - [ ] Option 2: Write custom potree pointcloud loader (unknown)

#### Total Time (Bottom Up):
Quick Path (Option 1, Option 1):
 - Time Estimate: 12-20 hrs
 - Time Estimate (100% safety margin): 24-40 hrs

Implementationally "Better" Path (Option 2, Option 1):
 - Time Estimate: 16-28 hrs
 - Time Estimate (100% safety margin): 32-56 hrs

Implementationally "Best" Path (Option 2, Option 2):
 - Time Estimate: ???
 - Time Estimate (100% safety margin): ??? 

## Sub-Task 3: Implementing Streaming Functionality (for pcaps):
_Top Down Time Estimate: 2-3 weeks after streaming flatbuffer solution_

#### Tasks
[todo]

#### Total Time (Bottom Up):
 - Time Estimate: [todo]
 - Time Estimate (100% safety margin): [todo]
